# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat May 17 06:18:53 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 672)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.booktab = QtGui.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.booktab.setFont(font)
        self.booktab.setObjectName("booktab")
        self.gridLayout = QtGui.QGridLayout(self.booktab)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setVerticalSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtGui.QLabel(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        self.betrag = QtGui.QLineEdit(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.betrag.sizePolicy().hasHeightForWidth())
        self.betrag.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.betrag.setFont(font)
        self.betrag.setObjectName("betrag")
        self.gridLayout_5.addWidget(self.betrag, 2, 3, 1, 1)
        self.beleg_nr = QtGui.QLineEdit(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beleg_nr.sizePolicy().hasHeightForWidth())
        self.beleg_nr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.beleg_nr.setFont(font)
        self.beleg_nr.setFrame(True)
        self.beleg_nr.setObjectName("beleg_nr")
        self.gridLayout_5.addWidget(self.beleg_nr, 0, 1, 1, 1)
        self.mwst_satz = QtGui.QComboBox(self.booktab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mwst_satz.setFont(font)
        self.mwst_satz.setObjectName("mwst_satz")
        self.gridLayout_5.addWidget(self.mwst_satz, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 3, 0, 1, 1)
        self.buchungs_txt = QtGui.QLineEdit(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buchungs_txt.sizePolicy().hasHeightForWidth())
        self.buchungs_txt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buchungs_txt.setFont(font)
        self.buchungs_txt.setObjectName("buchungs_txt")
        self.gridLayout_5.addWidget(self.buchungs_txt, 3, 1, 1, 1)
        self.add_booking_btn = QtGui.QPushButton(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_booking_btn.sizePolicy().hasHeightForWidth())
        self.add_booking_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.add_booking_btn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_booking_btn.setIcon(icon)
        self.add_booking_btn.setIconSize(QtCore.QSize(16, 16))
        self.add_booking_btn.setObjectName("add_booking_btn")
        self.gridLayout_5.addWidget(self.add_booking_btn, 3, 3, 1, 1)
        self.label = QtGui.QLabel(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 2, 1, 1)
        self.dateEdit = QtGui.QDateEdit(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dateEdit.setFont(font)
        self.dateEdit.setDate(QtCore.QDate(2014, 4, 23))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_5.addWidget(self.dateEdit, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 1, 0, 1, 1)
        self.soll_kto = QtGui.QLineEdit(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soll_kto.sizePolicy().hasHeightForWidth())
        self.soll_kto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.soll_kto.setFont(font)
        self.soll_kto.setObjectName("soll_kto")
        self.gridLayout_5.addWidget(self.soll_kto, 1, 1, 1, 1)
        self.haben_ktos = QtGui.QLineEdit(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.haben_ktos.sizePolicy().hasHeightForWidth())
        self.haben_ktos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.haben_ktos.setFont(font)
        self.haben_ktos.setObjectName("haben_ktos")
        self.gridLayout_5.addWidget(self.haben_ktos, 1, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.sammelbuchung_btn = QtGui.QPushButton(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sammelbuchung_btn.sizePolicy().hasHeightForWidth())
        self.sammelbuchung_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sammelbuchung_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/page_text_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sammelbuchung_btn.setIcon(icon1)
        self.sammelbuchung_btn.setIconSize(QtCore.QSize(16, 16))
        self.sammelbuchung_btn.setObjectName("sammelbuchung_btn")
        self.gridLayout.addWidget(self.sammelbuchung_btn, 0, 1, 1, 1)
        self.del_booking_btn = QtGui.QPushButton(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_booking_btn.sizePolicy().hasHeightForWidth())
        self.del_booking_btn.setSizePolicy(sizePolicy)
        self.del_booking_btn.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.del_booking_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_booking_btn.setIcon(icon2)
        self.del_booking_btn.setObjectName("del_booking_btn")
        self.gridLayout.addWidget(self.del_booking_btn, 3, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.booktab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(235, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 221, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.soll_kto_lbl = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.soll_kto_lbl.setFont(font)
        self.soll_kto_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soll_kto_lbl.setObjectName("soll_kto_lbl")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.soll_kto_lbl)
        self.soll_saldo = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soll_saldo.sizePolicy().hasHeightForWidth())
        self.soll_saldo.setSizePolicy(sizePolicy)
        self.soll_saldo.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.soll_saldo.setFont(font)
        self.soll_saldo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soll_saldo.setObjectName("soll_saldo")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.soll_saldo)
        self.haben_kto_lbl = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.haben_kto_lbl.setFont(font)
        self.haben_kto_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.haben_kto_lbl.setObjectName("haben_kto_lbl")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.haben_kto_lbl)
        self.haben_saldo = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.haben_saldo.sizePolicy().hasHeightForWidth())
        self.haben_saldo.setSizePolicy(sizePolicy)
        self.haben_saldo.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.haben_saldo.setFont(font)
        self.haben_saldo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.haben_saldo.setObjectName("haben_saldo")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.haben_saldo)
        self.gridLayout.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.buchungen = QtGui.QTreeWidget(self.booktab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buchungen.setFont(font)
        self.buchungen.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.buchungen.setFrameShape(QtGui.QFrame.StyledPanel)
        self.buchungen.setAlternatingRowColors(True)
        self.buchungen.setRootIsDecorated(False)
        self.buchungen.setItemsExpandable(True)
        self.buchungen.setObjectName("buchungen")
        self.buchungen.header().setDefaultSectionSize(120)
        self.buchungen.header().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.buchungen, 2, 0, 1, 5)
        self.tabWidget.addTab(self.booktab, "")
        self.settingstab = QtGui.QWidget()
        self.settingstab.setObjectName("settingstab")
        self.gridLayout_3 = QtGui.QGridLayout(self.settingstab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_3 = QtGui.QGroupBox(self.settingstab)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 181, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bilanz_chk = QtGui.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bilanz_chk.setFont(font)
        self.bilanz_chk.setObjectName("bilanz_chk")
        self.verticalLayout_2.addWidget(self.bilanz_chk)
        self.konto_chk = QtGui.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.konto_chk.setFont(font)
        self.konto_chk.setObjectName("konto_chk")
        self.verticalLayout_2.addWidget(self.konto_chk)
        self.er_chk = QtGui.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.er_chk.setFont(font)
        self.er_chk.setObjectName("er_chk")
        self.verticalLayout_2.addWidget(self.er_chk)
        self.plan_chk = QtGui.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.plan_chk.setFont(font)
        self.plan_chk.setObjectName("plan_chk")
        self.verticalLayout_2.addWidget(self.plan_chk)
        self.nullein_chk = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.nullein_chk.setObjectName("nullein_chk")
        self.verticalLayout_2.addWidget(self.nullein_chk)
        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.show_report_btn = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.show_report_btn.setFont(font)
        self.show_report_btn.setDefault(True)
        self.show_report_btn.setObjectName("show_report_btn")
        self.verticalLayout_2.addWidget(self.show_report_btn)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.settingstab)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edit_ktoplan_btn = QtGui.QPushButton(self.groupBox_2)
        self.edit_ktoplan_btn.setObjectName("edit_ktoplan_btn")
        self.horizontalLayout_2.addWidget(self.edit_ktoplan_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 3, 0, 1, 3)
        self.groupBox = QtGui.QGroupBox(self.settingstab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setHorizontalSpacing(6)
        self.formLayout_2.setVerticalSpacing(2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.mand_name = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mand_name.setFont(font)
        self.mand_name.setObjectName("mand_name")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.mand_name)
        self.label_8 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.mand_address = QtGui.QPlainTextEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mand_address.sizePolicy().hasHeightForWidth())
        self.mand_address.setSizePolicy(sizePolicy)
        self.mand_address.setMinimumSize(QtCore.QSize(0, 0))
        self.mand_address.setMaximumSize(QtCore.QSize(16777215, 60))
        self.mand_address.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mand_address.setFont(font)
        self.mand_address.setTabChangesFocus(True)
        self.mand_address.setObjectName("mand_address")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.mand_address)
        self.label_11 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_11)
        self.mwst_1 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mwst_1.setFont(font)
        self.mwst_1.setObjectName("mwst_1")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.mwst_1)
        self.label_12 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_12)
        self.mwst_2 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mwst_2.setFont(font)
        self.mwst_2.setObjectName("mwst_2")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.mwst_2)
        self.label_13 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_13)
        self.mwst_3 = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mwst_3.setFont(font)
        self.mwst_3.setObjectName("mwst_3")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.mwst_3)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.gridLayout_4.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.tabWidget.addTab(self.settingstab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_Mand = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/user_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("../../../.designer/backup/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNew_Mand.setIcon(icon3)
        self.actionNew_Mand.setObjectName("actionNew_Mand")
        self.actionSave = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        self.actionSave.setObjectName("actionSave")
        self.action_open = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap("../../../.designer/backup/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_open.setIcon(icon5)
        self.action_open.setObjectName("action_open")
        self.toolBar.addAction(self.actionNew_Mand)
        self.toolBar.addAction(self.action_open)
        self.toolBar.addAction(self.actionSave)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.add_booking_btn, QtCore.SIGNAL("clicked()"), self.buchungen.expandAll)
        QtCore.QObject.connect(self.soll_kto, QtCore.SIGNAL("textChanged(QString)"), self.soll_kto_lbl.setText)
        QtCore.QObject.connect(self.haben_ktos, QtCore.SIGNAL("textChanged(QString)"), self.haben_kto_lbl.setText)
        QtCore.QObject.connect(self.buchungs_txt, QtCore.SIGNAL("returnPressed()"), self.add_booking_btn.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.beleg_nr, self.dateEdit)
        MainWindow.setTabOrder(self.dateEdit, self.soll_kto)
        MainWindow.setTabOrder(self.soll_kto, self.haben_ktos)
        MainWindow.setTabOrder(self.haben_ktos, self.mwst_satz)
        MainWindow.setTabOrder(self.mwst_satz, self.betrag)
        MainWindow.setTabOrder(self.betrag, self.buchungs_txt)
        MainWindow.setTabOrder(self.buchungs_txt, self.add_booking_btn)
        MainWindow.setTabOrder(self.add_booking_btn, self.buchungen)
        MainWindow.setTabOrder(self.buchungen, self.mand_name)
        MainWindow.setTabOrder(self.mand_name, self.mand_address)
        MainWindow.setTabOrder(self.mand_address, self.mwst_1)
        MainWindow.setTabOrder(self.mwst_1, self.mwst_2)
        MainWindow.setTabOrder(self.mwst_2, self.mwst_3)
        MainWindow.setTabOrder(self.mwst_3, self.bilanz_chk)
        MainWindow.setTabOrder(self.bilanz_chk, self.konto_chk)
        MainWindow.setTabOrder(self.konto_chk, self.er_chk)
        MainWindow.setTabOrder(self.er_chk, self.plan_chk)
        MainWindow.setTabOrder(self.plan_chk, self.show_report_btn)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Meteor-Accounting v0.1b", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "MwSt-Satz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Belegnummer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Konto HABEN</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Betrag", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.add_booking_btn.setText(QtGui.QApplication.translate("MainWindow", "Buchen", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Datum", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd.MM.yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Konto SOLL", None, QtGui.QApplication.UnicodeUTF8))
        self.sammelbuchung_btn.setText(QtGui.QApplication.translate("MainWindow", "Sammelbuchung", None, QtGui.QApplication.UnicodeUTF8))
        self.del_booking_btn.setText(QtGui.QApplication.translate("MainWindow", "Ausgewählte Buchung löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Aktuelle Saldi", None, QtGui.QApplication.UnicodeUTF8))
        self.soll_kto_lbl.setText(QtGui.QApplication.translate("MainWindow", "Soll Konto", None, QtGui.QApplication.UnicodeUTF8))
        self.soll_saldo.setText(QtGui.QApplication.translate("MainWindow", "Saldo", None, QtGui.QApplication.UnicodeUTF8))
        self.haben_kto_lbl.setText(QtGui.QApplication.translate("MainWindow", "Haben Konto", None, QtGui.QApplication.UnicodeUTF8))
        self.haben_saldo.setText(QtGui.QApplication.translate("MainWindow", "Saldo", None, QtGui.QApplication.UnicodeUTF8))
        self.buchungen.setSortingEnabled(False)
        self.buchungen.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Nr", None, QtGui.QApplication.UnicodeUTF8))
        self.buchungen.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Belegnummer", None, QtGui.QApplication.UnicodeUTF8))
        self.buchungen.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Datum", None, QtGui.QApplication.UnicodeUTF8))
        self.buchungen.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Konto", None, QtGui.QApplication.UnicodeUTF8))
        self.buchungen.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Betrag", None, QtGui.QApplication.UnicodeUTF8))
        self.buchungen.headerItem().setText(5, QtGui.QApplication.translate("MainWindow", "Gegenkonto", None, QtGui.QApplication.UnicodeUTF8))
        self.buchungen.headerItem().setText(6, QtGui.QApplication.translate("MainWindow", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.buchungen.headerItem().setText(7, QtGui.QApplication.translate("MainWindow", "MwSt-Satz", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.booktab), QtGui.QApplication.translate("MainWindow", "Buchungen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Berichte anzeigen / drucken", None, QtGui.QApplication.UnicodeUTF8))
        self.bilanz_chk.setText(QtGui.QApplication.translate("MainWindow", "Bilanz", None, QtGui.QApplication.UnicodeUTF8))
        self.konto_chk.setText(QtGui.QApplication.translate("MainWindow", "Kontoauszüge (alle)", None, QtGui.QApplication.UnicodeUTF8))
        self.er_chk.setText(QtGui.QApplication.translate("MainWindow", "Erfolgsrechnung", None, QtGui.QApplication.UnicodeUTF8))
        self.plan_chk.setText(QtGui.QApplication.translate("MainWindow", "Kontenplan", None, QtGui.QApplication.UnicodeUTF8))
        self.nullein_chk.setText(QtGui.QApplication.translate("MainWindow", "Konten mit Nullsaldo\n"
"einblenden", None, QtGui.QApplication.UnicodeUTF8))
        self.show_report_btn.setText(QtGui.QApplication.translate("MainWindow", "Anzeigen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Kontenplan / Saldoübersicht", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_ktoplan_btn.setText(QtGui.QApplication.translate("MainWindow", "Kontenplan bearbeiten", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Mandanteninformationen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Mandantenname (kurz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Mandantenadresse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "MwSt - Satz 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "MwSt - Satz 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "MwSt - Satz 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Speicherort", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Änderungen speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingstab), QtGui.QApplication.translate("MainWindow", "Mandant / Berichte", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Mand.setText(QtGui.QApplication.translate("MainWindow", "Neuer Mandant", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Mand.setToolTip(QtGui.QApplication.translate("MainWindow", "Einen neuen Mandanten erstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("MainWindow", "Aktuellen Mandant speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setText(QtGui.QApplication.translate("MainWindow", "Öffnen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setToolTip(QtGui.QApplication.translate("MainWindow", "Einen gespeicherten Mandanten öffnen", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
