# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mandanten_erstellen.ui'
#
# Created: Sat May 17 06:05:04 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MandantenWizard(object):
    def setupUi(self, MandantenWizard):
        MandantenWizard.setObjectName("MandantenWizard")
        MandantenWizard.resize(543, 394)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/user_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MandantenWizard.setWindowIcon(icon)
        MandantenWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setAutoFillBackground(False)
        self.wizardPage1.setObjectName("wizardPage1")
        self.formLayoutWidget = QtGui.QWidget(self.wizardPage1)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 511, 261))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.mand_name = QtGui.QLineEdit(self.formLayoutWidget)
        self.mand_name.setObjectName("mand_name")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.mand_name)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.mand_address = QtGui.QTextEdit(self.formLayoutWidget)
        self.mand_address.setObjectName("mand_address")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.mand_address)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.mwst1 = QtGui.QLineEdit(self.formLayoutWidget)
        self.mwst1.setFrame(True)
        self.mwst1.setObjectName("mwst1")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.mwst1)
        self.mwst2 = QtGui.QLineEdit(self.formLayoutWidget)
        self.mwst2.setObjectName("mwst2")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.mwst2)
        self.mwst3 = QtGui.QLineEdit(self.formLayoutWidget)
        self.mwst3.setObjectName("mwst3")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.mwst3)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        MandantenWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.verticalLayoutWidget = QtGui.QWidget(self.wizardPage2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 521, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_kto_btn = QtGui.QPushButton(self.verticalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/page_text_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_kto_btn.setIcon(icon1)
        self.new_kto_btn.setObjectName("new_kto_btn")
        self.horizontalLayout.addWidget(self.new_kto_btn)
        self.del_kto_btn = QtGui.QPushButton(self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_kto_btn.setIcon(icon2)
        self.del_kto_btn.setObjectName("del_kto_btn")
        self.horizontalLayout.addWidget(self.del_kto_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.kontenplan = QtGui.QTreeView(self.verticalLayoutWidget)
        self.kontenplan.setObjectName("kontenplan")
        self.verticalLayout.addWidget(self.kontenplan)
        MandantenWizard.addPage(self.wizardPage2)

        self.retranslateUi(MandantenWizard)
        QtCore.QMetaObject.connectSlotsByName(MandantenWizard)

    def retranslateUi(self, MandantenWizard):
        MandantenWizard.setWindowTitle(QtGui.QApplication.translate("MandantenWizard", "Neuen Mandanten erstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage1.setTitle(QtGui.QApplication.translate("MandantenWizard", "Neuen Mandanten erstellen (1/2)", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage1.setSubTitle(QtGui.QApplication.translate("MandantenWizard", "Bitte geben Sie die Informationen zum neuen Mandanten ein.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MandantenWizard", "Mandantenname (Kurz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MandantenWizard", "Mandantenadresse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MandantenWizard", "MwSt-Satz 1", None, QtGui.QApplication.UnicodeUTF8))
        self.mwst1.setInputMask(QtGui.QApplication.translate("MandantenWizard", "0.0 %; ", None, QtGui.QApplication.UnicodeUTF8))
        self.mwst2.setInputMask(QtGui.QApplication.translate("MandantenWizard", "0.0 %; ", None, QtGui.QApplication.UnicodeUTF8))
        self.mwst3.setInputMask(QtGui.QApplication.translate("MandantenWizard", "0.0 %; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MandantenWizard", "MwSt-Satz 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MandantenWizard", "MwSt-Satz 3", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage2.setTitle(QtGui.QApplication.translate("MandantenWizard", "Neuen Mandanten erstellen (2/2)", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage2.setSubTitle(QtGui.QApplication.translate("MandantenWizard", "Bitte passen Sie den Kontenplan sowie die Anfangssaldi an.", None, QtGui.QApplication.UnicodeUTF8))
        self.new_kto_btn.setText(QtGui.QApplication.translate("MandantenWizard", "Neues Konto hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.del_kto_btn.setText(QtGui.QApplication.translate("MandantenWizard", "Konto löschen", None, QtGui.QApplication.UnicodeUTF8))

